config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get "auth/github/callback", to: "sessions#create"

  resources :users, only: [:new, :edit, :update]
  resources :matches, only: [:index]
  resources :user_matches, only: [:create]
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :user_languages
  has_many :users, through: :user_languages
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :languages, through: :user_languages
  has_many :user_languages
  validates :about, length: { maximum: 500 }

  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(uid: data.uid)

    user.name      = data.info.name
    user.image_url = data.info.image
    user.username  = data.info.nickname
    user.save
    user
  end

  def available_matches
    User.where.not(id: match_restrictions)
  end

  def pending_approvals
    User.where(id: half_approved_matches)
  end

  def match_restrictions
    restricted_ids = []
    restricted_ids << current_user_id
    restricted_ids << pending_matches_as_initiator
    restricted_ids << pending_matches_as_invitee
    restricted_ids << rejected_matches_as_initiator
    restricted_ids << rejected_matches_as_invitee
    restricted_ids << approved_matches_as_initiator
    restricted_ids << approved_matches_as_invitee
    restricted_ids.flatten.uniq
  end

  def half_approved_matches
    half_approved = []
    half_approved << pending_matches_as_invitee
    half_approved.flatten.uniq
  end

  def matches
    find_matched_user.map { |id| User.find(id) }
  end

  private

  def current_user_id
    self.id
  end

  def pending_matches_as_initiator
    matches = UserMatch.where(initiator_id: self.id, match_status: "pending")
    matches.pluck("initiator_id", "invitee_id")
  end

  def pending_matches_as_invitee
    matches = UserMatch.where(invitee_id: self.id, match_status: "pending")
    matches.pluck("initiator_id")
  end

  def rejected_matches_as_initiator
    matches = UserMatch.where(initiator_id: self.id, match_status: "rejected")
    matches.pluck("initiator_id", "invitee_id")
  end

  def rejected_matches_as_invitee
    matches = UserMatch.where(invitee_id: self.id, match_status: "rejected")
    matches.pluck("initiator_id", "invitee_id")
  end

  def approved_matches_as_initiator
    matches = UserMatch.where(initiator_id: self.id, match_status: "approved")
    matches.pluck("initiator_id", "invitee_id")
  end

  def approved_matches_as_invitee
    matches = UserMatch.where(invitee_id: self.id, match_status: "approved")
    matches.pluck("initiator_id", "invitee_id")
  end
  def find_matched_user
    UserMatch.where(initiator_id: self.id, match_status: "approved").pluck(:invitee_id) +
    UserMatch.where(invitee_id: self.id, match_status: "approved").pluck(:initiator_id)
  end
end

app/models/user_language.rb
class UserLanguage < ActiveRecord::Base
  belongs_to :user
  belongs_to :language
end

app/models/user_match.rb
class UserMatch < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :next_possibility, :authorize!

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def next_possibility
    @next_possibility ||= current_user.available_matches.sample
  end

  def awaiting_approval
    @awaiting_approval ||= current_user.pending_approvals.sample
  end

  def authorize!
    redirect_to new_user_path unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize!, only: [:index]

  def index
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authorize!, only: [:index]
  def index
    @awaiting_approval = awaiting_approval
    @possible_match = next_possibility
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    @user = User.find_or_create_from_auth(auth)
    if new_user?
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user)
    elsif @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged In"
    else
      redirect_to new_user_path, notice: "Invalid"
    end
  end

  private

  def new_user?
    @user && @user.about == nil
  end
end

app/controllers/user_matches_controller.rb
class UserMatchesController < ApplicationController

  def create
    already_match = UserMatch.where(initiator_id: current_user.id, invitee_id: params[:invitee_id]).first || UserMatch.where(invitee_id: current_user.id, initiator_id: params[:invitee_id]).first

    if !already_match
      if params[:status]
        UserMatch.create(initiator_id: current_user.id, invitee_id: params[:invitee_id], match_status: params[:status] )
      else
        UserMatch.create(initiator_id: current_user.id, invitee_id: params[:invitee_id])
      end
    elsif already_match.match_status == "pending"
      already_match.update(match_status: "approved")
      flash[:success] = "Congrats! You have a match"
    else
      already_match.update(match_status: "rejected")
    end
    redirect_to matches_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def edit
    @user = User.find(params[:id])
    @languages = Language.all
  end

  def update
    current_user.update(about: params[:user][:about])

    languages.each do |id|
      UserLanguage.create(user_id: current_user.id, language_id: id)
    end

    redirect_to root_path
  end

  private

  def languages
    params[:user][:languages].shift
    params[:user][:languages]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="text-center container">
  <h1> Welcome To Pairr </h1>
  <br><br>
  <%= link_to "Find Pairs", matches_path, class: "btn btn-success" %>
  <% if current_user.matches %>
  <br><br><br><br>
    <% current_user.matches.each do |match| %>
    <h4>You've been matched! Time to pair </h4>
      <%= "#{current_user.username} + #{match.username} are a match!" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
  <% end %>
</div>

</body>
</html>

app/views/matches/index.html.erb
<div align="center">

  <% if @awaiting_approval  %>
      <%= image_tag(@awaiting_approval.image_url, class: "profile-picture") %>
      <h3>Name: <%= @awaiting_approval.name %> </h3>
      <h3>GitHub username: <%= @awaiting_approval.username %></h3>
      <h3>About Me: <%= @awaiting_approval.about %></h3>
      <% @awaiting_approval.languages.each do |language| %>
        <h5> <%= language.name %> </h5>
      <% end %>
      <div class="btn-group">
        <%= link_to "Accept", user_matches_path(invitee_id: @awaiting_approval.id), method: :post, class: "btn btn-success" %>
        <%= link_to "Reject", user_matches_path(invitee_id: @awaiting_approval.id, status: "rejected"), method: :post, class: "btn btn-danger" %>
      </div>
  <% elsif next_possibility  %>
      <%= image_tag(@possible_match.image_url, class: "profile-picture") %>
      <h3>Name: <%= @possible_match.name %></h3>
      <h3>GitHub username: <%= @possible_match.username %></h3>
      <h3>About Me: <%= @possible_match.about %></h3>
      <% @possible_match.languages.each do |language| %>
        <h5> <%= language.name %> </h5>
      <% end %>
      <div class="btn-group">
        <%= link_to "Accept", user_matches_path(invitee_id: @possible_match.id), method: :post, class: "btn btn-success" %>
        <%= link_to "Reject", user_matches_path(invitee_id: @possible_match.id, status: "rejected"), method: :post, class: "btn btn-danger" %>
      </div>
  <% else %>
    <p>There aren't any more users... Tell your friends!</p>
  <% end %>
</div>

app/views/users/edit.html.erb
<div align="center">
  <h2> Please Tell Us Some More Information </h2>
  <br><br>
  <%= bootstrap_form_for @user do |f| %>
    <div class="container">
      <%= f.text_area :about, label: "Some Information About Yourself -- Maximum 500 Characters" %>
    </div>
    <%= f.collection_check_boxes :languages, @languages, :id, :name %>
    <%= f.submit "Update Your Information", class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div align="center">
  <h1> Please Register an Account </h1>
  <br><br>
  <%= link_to "Login With GitHub", "/auth/github", class: "btn btn-success" %>
</div>